spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    kr.co.nonghyup.sangho.infosystem: INFO
